---
- hosts: all
  become: true
#  vars:
#    my_name: jinge
  roles:
     - role: jinge.wordpress
       database_name: jingewp
       database_user: jingewp
       database_password: bananas
       wp_domain: book.example.com
       initial_post_title: Jinge Is Here
       initial_post_content: This is an example post. Change me to say something interesting.