---
# tasks file for jinge.dockerized
- name: Pull rastasheep's ubuntu-sshd image
  docker_image:
    name: rastasheep/ubuntu-sshd

- name: Create a docker container from the rastasheep/ubuntu-sshd image, port forward 22 to 2222
  docker_container:
    name: sshdserver
    image: rastasheep/ubuntu-sshd
    ports:
      - "2222:22"
    command: /usr/sbin/sshd -D

- add_host:
    name: "docker-container"
    ansible_host: "{{ansible_default_ipv4.address}}"
    ansible_port: 2222
    ansible_user: vagrant
    ansible_password: vagrant

- name: Install sshpass
  apt: name=sshpass state=installed
